/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/core/core.hpp>
#include <opencv2/imgproc/imgproc_c.h>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/opencv.hpp>
#include <vector>
#include <string>
#include <android/log.h>
#include <sstream>

using namespace cv;
using namespace std;

/* Header for class com_aveti_omr_JNIProcess */

#ifndef _Included_com_aveti_omr_JNIProcess
#define _Included_com_aveti_omr_JNIProcess
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jfloatArray JNICALL Java_com_aveti_omr_JNIProcess_getPoints
  (JNIEnv *env, jlong addrRgba);

JNIEXPORT jstring JNICALL Java_com_aveti_omr_JNIProcess_recogBubble
  (JNIEnv *env, jlong inputMat);

vector<Point> getPoints(Mat image);
double angle( cv::Point pt1, cv::Point pt2, cv::Point pt0 );
std::string to_string(int i);
int binToDec(std::string bin, int first, int length);
void sort_contour(std::vector<std::vector<cv::Point> > &contours, int from, int to, std::string sortOrder);

#ifdef __cplusplus
}
#endif
#endif
